# Generated by Django 2.2.7 on 2019-11-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='None', max_length=254)),
                ('server', models.GenericIPAddressField()),
                ('group', models.CharField(default='None', max_length=200)),
            ],
            options={
                'db_table': 'demo_user_group',
            },
        ),
    ]
